### ISSUE TITLE
change test intervals

### ISSUE THREAD

**Issue by robertronq** [vkentta/internet-speed-logger#1]
Hi. I was able this running, but was wondering if its possible to change the test interval? To something like every 1 or 2 hours, instead of every 15 mins? Thank you.

**Comment by vkentta** [comment]
Hi! Currently there is no config options available, but I might add some at some point. For now you can change this line of code https://github.com/vkentta/internet-speed-logger/blob/master/index.js#L7 to alter the interval.

**Comment by vkentta** [comment]
Added the requested functionality here: https://github.com/vkentta/internet-speed-logger/commit/141bbbc73ec575e8e7e94b2567ad56b355426fc3

You can set the desired interval by setting the `CHECK_PERIOD_MINUTES` env variable. So for example:
`-e CHECK_PERIOD_MINUTES=120`
would set the interval to 2 hours.

**Comment by robertronq** [comment]
This is great !!
Thank you very much for the quick reply !!

Regards,
Robert
